spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sicsu_site
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  freemarker:
    suffix: .ftl
    expose-request-attributes: true

upload.path: /C:/Users/sinit/OneDrive/Рабочий стол/Java/sicsu_files